//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lazy8.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lazy8.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos;, which has value &apos;{1}&apos;, is not between &apos;{2}&apos; and &apos;{3}&apos; (exclusive)..
        /// </summary>
        public static string Assert_BetweenExclusive {
            get {
                return ResourceManager.GetString("Assert_BetweenExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos;, which has value &apos;{1}&apos;, is not between &apos;{2}&apos; and &apos;{3}&apos; (inclusive)..
        /// </summary>
        public static string Assert_BetweenInclusive {
            get {
                return ResourceManager.GetString("Assert_BetweenInclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; is empty..
        /// </summary>
        public static string Assert_ContainerIsEmpty {
            get {
                return ResourceManager.GetString("Assert_ContainerIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string parameter &apos;{0}&apos; specifies directory &apos;{1}&apos; which does not exist..
        /// </summary>
        public static string Assert_DirectoryExists {
            get {
                return ResourceManager.GetString("Assert_DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos;, which has value &apos;{1}&apos;, is equal to &apos;{2}&apos;..
        /// </summary>
        public static string Assert_EqualTo {
            get {
                return ResourceManager.GetString("Assert_EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string parameter &apos;{0}&apos; specifies file &apos;{1}&apos; which does not exist..
        /// </summary>
        public static string Assert_FileExists {
            get {
                return ResourceManager.GetString("Assert_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos;, which has value &apos;{1}&apos;, is not equal to &apos;{2}&apos;..
        /// </summary>
        public static string Assert_NotEqualTo {
            get {
                return ResourceManager.GetString("Assert_NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos;, which has value &apos;{1}&apos;, is not greater than &apos;{2}&apos;..
        /// </summary>
        public static string Assert_NotGreaterThan {
            get {
                return ResourceManager.GetString("Assert_NotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos;, which has value &apos;{1}&apos;, is not greater than or equal to &apos;{2}&apos;..
        /// </summary>
        public static string Assert_NotGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Assert_NotGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos;, which has value &apos;{1}&apos;, is not less than &apos;{2}&apos;..
        /// </summary>
        public static string Assert_NotLessThan {
            get {
                return ResourceManager.GetString("Assert_NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos;, which has value &apos;{1}&apos;, is not less than or equal to &apos;{2}&apos;..
        /// </summary>
        public static string Assert_NotLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("Assert_NotLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimumLength parameter ({0}) cannot be greater than the maximumLength parameter ({1})..
        /// </summary>
        public static string Assert_StringInconsistentLengthParameters {
            get {
                return ResourceManager.GetString("Assert_StringInconsistentLengthParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string parameter &apos;{0}&apos; consists soley of whitespace..
        /// </summary>
        public static string Assert_StringIsAllWhitespace {
            get {
                return ResourceManager.GetString("Assert_StringIsAllWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of string parameter &apos;{0}&apos; ({1}) is greater than {2}..
        /// </summary>
        public static string Assert_StringLengthGreaterThanMaximum {
            get {
                return ResourceManager.GetString("Assert_StringLengthGreaterThanMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of string parameter &apos;{0}&apos; ({1}) is less than {2}..
        /// </summary>
        public static string Assert_StringLengthLessThanMinimum {
            get {
                return ResourceManager.GetString("Assert_StringLengthLessThanMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length of string parameter &apos;{0}&apos; ({1}) does not equal {2}..
        /// </summary>
        public static string Assert_StringLengthsNotEqual {
            get {
                return ResourceManager.GetString("Assert_StringLengthsNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string parameter &apos;{0}&apos; cannot consist only of whitespace..
        /// </summary>
        public static string Assert_StringNotWhitespace {
            get {
                return ResourceManager.GetString("Assert_StringNotWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string parameter &apos;{0}&apos; cannot have a length of zero..
        /// </summary>
        public static string Assert_StringNotZeroLength {
            get {
                return ResourceManager.GetString("Assert_StringNotZeroLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A quarter of {0} is not valid. quarter must be between 1 and 4 inclusive..
        /// </summary>
        public static string DateTimeUtils_QuarterNotInRange {
            get {
                return ResourceManager.GetString("DateTimeUtils_QuarterNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        public static string Exceptions_File_Does_Not_Exist {
            get {
                return ResourceManager.GetString("Exceptions_File_Does_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing file is &apos;{0}&apos;..
        /// </summary>
        public static string Exceptions_MissingFile {
            get {
                return ResourceManager.GetString("Exceptions_MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Trace:
        ///{0}.
        /// </summary>
        public static string Exceptions_StackTrace {
            get {
                return ResourceManager.GetString("Exceptions_StackTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;otherBaseNumber&apos; ({0}) contains digits that are not valid for the parameter &apos;fromBase&apos; {1}..
        /// </summary>
        public static string MathUtils_BadDigit {
            get {
                return ResourceManager.GetString("MathUtils_BadDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown RangeCheck value ({0})..
        /// </summary>
        public static string MathUtils_BadRangeCheckValue {
            get {
                return ResourceManager.GetString("MathUtils_BadRangeCheckValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;toBase&apos; has an illegal value of {0}.  toBase must be between 2 and 36, inclusive..
        /// </summary>
        public static string MathUtils_BaseOutOfRange {
            get {
                return ResourceManager.GetString("MathUtils_BaseOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;min&apos; ({0}) is greater than the parameter &apos;max&apos; ({1})..
        /// </summary>
        public static string MathUtils_MinGreaterThanMax {
            get {
                return ResourceManager.GetString("MathUtils_MinGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;count&apos; ({0}) must be greater than zero..
        /// </summary>
        public static string Random_CountOutOfRange {
            get {
                return ResourceManager.GetString("Random_CountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;lowChar&apos; ({0}) must be less than &apos;highChar&apos; ({1})..
        /// </summary>
        public static string Random_LowCharGreaterThanHighChar {
            get {
                return ResourceManager.GetString("Random_LowCharGreaterThanHighChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;lowDate&apos; ({0}) must be less than or equal to &apos;highDate&apos; ({1})..
        /// </summary>
        public static string Random_LowDateGreaterThanHighDate {
            get {
                return ResourceManager.GetString("Random_LowDateGreaterThanHighDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;low&apos; ({0}) must be less than &apos;high&apos; ({1})..
        /// </summary>
        public static string Random_LowGreaterThanHigh {
            get {
                return ResourceManager.GetString("Random_LowGreaterThanHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;lowTimeSpan&apos; ({0}) must be less than or equal to &apos;highTimeSpan&apos; ({1})..
        /// </summary>
        public static string Random_LowTimeSpanGreaterThanHighDate {
            get {
                return ResourceManager.GetString("Random_LowTimeSpanGreaterThanHighDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;probability&apos; ({0}) must be between 0.0 and 1.0, exclusive..
        /// </summary>
        public static string Random_ProbabilityNotInRange {
            get {
                return ResourceManager.GetString("Random_ProbabilityNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown value of LetterCaseMix enumeration ({0})..
        /// </summary>
        public static string Random_UnknownLetterCaseMixValue {
            get {
                return ResourceManager.GetString("Random_UnknownLetterCaseMixValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; was not found..
        /// </summary>
        public static string Reflection_PropertyNotFound {
            get {
                return ResourceManager.GetString("Reflection_PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no previously saved position.  Are you missing a call to SavePosition()?.
        /// </summary>
        public static string StringScanner_NoSavedPosition {
            get {
                return ResourceManager.GetString("StringScanner_NoSavedPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no previously saved position available to go back to.  Are you missing a call to SavePosition()?.
        /// </summary>
        public static string StringScanner_NoSavedPositionToGoBackTo {
            get {
                return ResourceManager.GetString("StringScanner_NoSavedPositionToGoBackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter &apos;{0}&apos; cannot be null..
        /// </summary>
        public static string StringScanner_NullConstructorValue {
            get {
                return ResourceManager.GetString("StringScanner_NullConstructorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;indent&apos; parameter has a value of &apos;{0}&apos;.  It must be between 0 and Int32.MaxValue, inclusive..
        /// </summary>
        public static string StringUtils_BadIndent {
            get {
                return ResourceManager.GetString("StringUtils_BadIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t know how to process &apos;{0}&apos;..
        /// </summary>
        public static string StringUtils_BadRangeFormat {
            get {
                return ResourceManager.GetString("StringUtils_BadRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,Y,T,TRUE,YES.
        /// </summary>
        public static string StringUtils_BooleanTruthLiterals {
            get {
                return ResourceManager.GetString("StringUtils_BooleanTruthLiterals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of the parameters are either null, have zero length, or consist only of whitespace..
        /// </summary>
        public static string StringUtils_Coalesce {
            get {
                return ResourceManager.GetString("StringUtils_Coalesce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; does not contain either the * or ? characters..
        /// </summary>
        public static string StringUtils_RegexFilemask {
            get {
                return ResourceManager.GetString("StringUtils_RegexFilemask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No declaring type could be found for stack frame {0}..
        /// </summary>
        public static string Utils_NoDeclaringTypeFoundOnStackFrame {
            get {
                return ResourceManager.GetString("Utils_NoDeclaringTypeFoundOnStackFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No executing method could be found for stack frame {0}..
        /// </summary>
        public static string Utils_NoMethodFoundOnStackFrame {
            get {
                return ResourceManager.GetString("Utils_NoMethodFoundOnStackFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No stack frame exists at level {0}..
        /// </summary>
        public static string Utils_NoStackFrameExists {
            get {
                return ResourceManager.GetString("Utils_NoStackFrameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A call to Process.Start() returned null.  The command &apos;{0}&apos; could not be executed.  It may be a URL, or there&apos;s already a process running that command..
        /// </summary>
        public static string Utils_ProcessCouldNotBeStarted {
            get {
                return ResourceManager.GetString("Utils_ProcessCouldNotBeStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown RunProcessType value ({0})..
        /// </summary>
        public static string Utils_UnknownRunProcessType {
            get {
                return ResourceManager.GetString("Utils_UnknownRunProcessType", resourceCulture);
            }
        }
    }
}
